# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Installing
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
          
      - name: Generate
        uses: CultureHQ/actions-yarn@master
        with:
          args: generate
          
      - run : ls
      
      - name: Deploy to my ❤️
        uses: up9cloud/action-rsync@v1.1
        env:
          HOST: example.com
          KEY: ${{secrets.SSH_KEY}}
          TARGET: /sites/tests.timotheedurand.fr/
          SOURCE: ./dist
          VERBOSE: true
          USER: ${{ secrets.SSH_USER }}
          PRE_SCRIPT: |
            echo start at:
            date -u
          POST_SCRIPT: "echo done at: && date -u"

      #- name: Deploying
       # uses: appleboy/ssh-action@master
        #with:
         # host: ${{ secrets.HOST }}
          #username: ${{ secrets.SSH_USER }}
          #password: ${{ secrets.SSH_PSW }}
          #script: |
           # cd ./sites/tests.timotheedurand.fr/
            #git fetch
          
          
